version: "3"
services:
  backend:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=root
      - HOST=0.0.0.0
      - PORT=7654
      - GIN_MODE=release
    ports:
      - "7654:7654"
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    networks:
      - db
    logging:
      driver: none

networks:
  db: